apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
        - name: php-redis
          image: anjia0532/google-samples.gb-frontend:v5
          imagePullPolicy: IfNotPresent
          env:
            - name: GET_HOSTS_FROM
              value: "dns"
          ports:
            - containerPort: 80